### ISSUE TITLE
Train/Test Split used in the TPAMI Paper

### ISSUE THREAD

**Issue by carlosh93** [VITA-Group/PA-HMDB51#1]
Hello!

Thank you very much for creating this dataset. I am trying to replicate the results you reported in the TPAMI paper, and I would like to know how you split the videos from the PA-HMDB dataset? In order to compare my approach with yours, it is important to have the same train/test split. Would you please provide the train and test split files or explain how you split the dataset? 

Thank you!

**Comment by wuzhenyusjtu** [comment]
PA-HMDB51 is a subset of the HMDB51 dataset and it is used for EVALUATION only. We exclude the videos in the PA-HMDB51 from the HMDB51 to get the TRAINING set.

In detail, we use cross-training on HMDB51 (with videos in PA-HMDB51 excluded) + VISPR datasets similarly to the UCF-101 experiment; but for testing, we evaluate both utility and privacy performance on the same, newly-annotated PA-HMDB51.

You can find the videos name of PA-HMDB51 in the annotation files.

Here is attached the most updated paper. Please check Section 3.4 for training details and Section 5.5 for data split details.

**Comment by carlosh93** [comment]
Thank you so much!
